#===============================================================================
# * UseText handlers
#===============================================================================

ItemHandlers::UseText.add(:APRICORNCHARM, proc { |item|
  next ($player.activeCharm?(item)) ? _INTL("비활성") : _INTL("활성")
})

ItemHandlers::UseText.copy(:APRICORNCHARM, :BALANCECHARM, :BERRYCHARM, :CATCHINGCHARM, :CLOVERCHARM, :COINCHARM,
    :COLORCHARM, :CONTESTCHARM, :CORRUPTCHARM, :CRAFTINGCHARM, :DISABLECHARM, :EASYCHARM, :EFFORTCHARM, :EXPALLCHARM,
    :EXPCHARM, :FRIENDSHIPCHARM, :FRUGALCHARM, :GENECHARM, :GOLDCHARM, :HEALINGCHARM, :HEARTCHARM,
    :HERITAGECHARM, :HIDDENCHARM, :IVCHARM, :KEYCHARM, :LINKCHARM, :LURECHARM, :MERCYCHARM, :MININGCHARM, :OVALCHARM,
    :POINTSCHARM, :PROMOCHARM, :PURECHARM, :ROAMINGCHARM, :RESISTORCHARM, :SAFARICHARM, :SHINYCHARM, :SLOTSCHARM,
    :SMARTCHARM, :SPIRITCHARM, :STABCHARM, :STEPCHARM, :TRADINGCHARM, :TRIPTRIADCHARM, :TWINCHARM, :VIRALCHARM,
    :WISHINGCHARM, :BUGCHARM, :DARKCHARM, :DRAGONCHARM, :ELECTRICCHARM, :FAIRYCHARM, :FIGHTINGCHARM, :FIRECHARM,
    :FLYINGCHARM, :GHOSTCHARM, :GRASSCHARM, :GROUNDCHARM, :ICECHARM, :NORMALCHARM, :POISONCHARM, :PSYCHICCHARM,
    :ROCKCHARM, :STEELCHARM, :WATERCHARM)